In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('analytics_report_2026-03-30_10_15.xlsx', skiprows = 4)

In [4]:
df.head(3)

,Название товара,Ссылка на товар,Продавец,Бренд,Категория 1 уровня,Категория 3 уровня,Признак товара,"Заказано на сумму, ₽","Динамика оборота, %","Заказано, штуки",...,Просмотры карточки,"Конверсия из показа в заказ, %","В корзину из поиска и каталога, %","В корзину из карточки, %",Скидка за счет акций,"Доля оборота в акциях, %",Дней в акциях,Дней с продвижением,"Доля рекламных расходов, %",Дата создания карточки товара
0,Среднее значение по товарам,NaN,NaN,NaN,NaN,NaN,NaN,493570,266,906,...,15224,0.28,3.68,10.01,18.7,63.1,20 из 28,13 из 28,7.4,NaN
1,Чай Пора заварить весенний набор,https://www.ozon.ru/product/3542297512,beFRUITbe,beFRUITbe,Продукты питания,Чай листовой,Лидер по продажам,5604617,110,1152,...,42419,0.35,1.47,4.62,0.0,0.0,0 из 28,0 из 28,0.0,2026-02-18
2,"Набор чая TiSun, чай листовой в баночках, 12 ш...",https://www.ozon.ru/product/1835159809,KOOh,TiSun,Продукты питания,Чай листовой,Лидер по продажам,4613284,66,4675,...,62017,0.25,0.21,10.89,54.6,99.0,28 из 28,21 из 28,3.8,2025-01-16

In [5]:
df = df[1:]

In [6]:
df.head(3)

,Название товара,Ссылка на товар,Продавец,Бренд,Категория 1 уровня,Категория 3 уровня,Признак товара,"Заказано на сумму, ₽","Динамика оборота, %","Заказано, штуки",...,Просмотры карточки,"Конверсия из показа в заказ, %","В корзину из поиска и каталога, %","В корзину из карточки, %",Скидка за счет акций,"Доля оборота в акциях, %",Дней в акциях,Дней с продвижением,"Доля рекламных расходов, %",Дата создания карточки товара
1,Чай Пора заварить весенний набор,https://www.ozon.ru/product/3542297512,beFRUITbe,beFRUITbe,Продукты питания,Чай листовой,Лидер по продажам,5604617,110,1152,...,42419,0.35,1.47,4.62,0.0,0.0,0 из 28,0 из 28,0.0,2026-02-18
2,"Набор чая TiSun, чай листовой в баночках, 12 ш...",https://www.ozon.ru/product/1835159809,KOOh,TiSun,Продукты питания,Чай листовой,Лидер по продажам,4613284,66,4675,...,62017,0.25,0.21,10.89,54.6,99.0,28 из 28,21 из 28,3.8,2025-01-16
3,Набор чая подарочный/ Подарок женщине / Чай на...,https://www.ozon.ru/product/1692557767,Пряный Мастер,Пряный Мастер,Продукты питания,Чай листовой,Лидер по продажам,4496097,310,3429,...,58568,0.15,0.09,9.29,20.8,100.0,28 из 28,12 из 28,7.8,2024-09-13

In [7]:
df = df.loc[:, ['Название товара', 'Бренд', 'Продавец', 'Признак товара', 'Заказано на сумму, ₽', 'Динамика оборота, %', 'Доля выкупа, %', 'Доля оборота в акциях, %']]

In [8]:
df.dtypes

Название товара              object
Бренд                        object
Продавец                     object
Признак товара               object
Заказано на сумму, ₽          int64
Динамика оборота, %          object
Доля выкупа, %               object
Доля оборота в акциях, %    float64
dtype: object

In [9]:
top_brands = df.groupby('Бренд')['Заказано на сумму, ₽'].sum()

In [10]:
top_brands.head(10)

Бренд
5:05 Время для себя     1330620
AVGift                  2631567
Ahmad Tea              11952143
AirTokyo™               1239056
Akbar                   3379411
Art of Tea               306534
Azercay                 2903237
BASKEY                  3240556
Basilur                 1962200
Beta Tea                 188259
Name: Заказано на сумму, ₽, dtype: int64

In [11]:
all_sum = df['Заказано на сумму, ₽'].sum()

In [12]:
all_sum

np.int64(493570237)

In [13]:
result = (top_brands.head(10) / all_sum) * 100

In [14]:
result

Бренд
5:05 Время для себя    0.269591
AVGift                 0.533170
Ahmad Tea              2.421569
AirTokyo™              0.251039
Akbar                  0.684687
Art of Tea             0.062105
Azercay                0.588212
BASKEY                 0.656554
Basilur                0.397552
Beta Tea               0.038142
Name: Заказано на сумму, ₽, dtype: float64

In [15]:
result_rename_column = result.reset_index(name = 'процент от оборота')

In [16]:
result_rename_column.to_excel('result_task_one.xlsx', index = False)